version: '3'

services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9_DNS
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - ./etc/bind/:/etc/bind/
    restart: unless-stopped
